### PR TITLE
fix php error with rank math seo

### LINKED ISSUE #2626: PHP error with the Rank Math SEO plugin
We've had a couple of reports of an error with the Rank Math SEO plugin:
```

Warning: Attempt to read property "labels" on bool in /home/a3m200/3m2.ua/www/wp-content/plugins/seo-by-rank-math/includes/settings/titles/taxonomies.php on line 15
Warning: Attempt to read property "singular_name" on null in /home/a3m200/3m2.ua/www/wp-content/plugins/seo-by-rank-math/includes/settings/titles/taxonomies.php on line 15
```

### PR DESCRIPTION
**Pull request by Deji98**
## Description
PHP error with the Rank Math SEO plugin #2626
## Benefits
fix #2626 

## Applicable issues
#2626 

## Checklist

- [x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x] This pull request relates to a specific problem (bug or improvement).
- [x] I have mentioned the issue number in the pull request description text.
- [x] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

### CODE REVIEW

**Review by ojopaul — APPROVED** [review]

File: inc/taxonomies-functions.php [hunk 1]
```diff
@@ -1977,16 +1977,46 @@ function taxopress_unregister_taxonomy($taxonomy)
...
+    }
 
     // Remove custom taxonomy default term option.
     if (!empty($taxonomy_object->default_term)) {
         delete_option('default_term_' . $taxonomy_object->name);
     }
 
     // Remove the taxonomy.
-    unset($wp_taxonomies[$taxonomy]);
+    //unset($wp_taxonomies[$taxonomy]);
```
Comment (ojopaul) [inline inc/taxonomies-functions.php:2019]: @Deji98 Remove this code completely instead of commenting it. If we keep the habit of commenting code after new changes instead of removing them, we'll end up with alot of unused code inside the plugin which is not ideal.

**Review by ojopaul — CHANGES_REQUESTED** [review]

File: inc/taxonomies-functions.php [hunk 2]
```diff
@@ -1977,17 +1977,44 @@ function taxopress_unregister_taxonomy($taxonomy)
...
     global $wp_taxonomies;
 
-    $taxonomy_object->remove_rewrite_rules();
-    $taxonomy_object->remove_hooks();
+    // Instead of removing totally, keep minimal structure but disable functionality
+   if (isset($wp_taxonomies[$taxonomy])) {
+        // Store original in case we need to restore
+        $original_tax = $wp_taxonomies[$taxonomy];
+        
+        $wp_taxonomies[$taxonomy] = new stdClass();
```
Comment (ojopaul) [inline inc/taxonomies-functions.php:1985]: @Deji98 Is there any reason you're creating new object instead of updating existing taxonomy data?

**Review by ojopaul — CHANGES_REQUESTED** [review]
